export const K=['peach','lav','lime','blue']
// Safe localStorage read: never crashes the app, even if the stored value is missing or corrupted (bad JSON).
export const ls=(k,d)=>{try{const v=localStorage.getItem(k);return v==null?d:JSON.parse(v)}catch{return d}}
export const NAV=[['Home','/'],['About','/about'],['Learning','/courses'],['Community','/community'],['Events','/#events'],['Business','/#business'],['Helping Hands','/#help'],['Contact','/contact']]
// Admin-managed content (frontend-only, stored per-browser). Admin panel adds/removes items
// with these; public pages merge the results in with the built-in defaults below.
export const adminList=(key)=>ls('admin_'+key,[])
export const adminAdd=(key,item)=>{const l=adminList(key);const n=[...l,{...item,_id:Date.now()+'-'+Math.random().toString(36).slice(2)}];localStorage.setItem('admin_'+key,JSON.stringify(n));return n}
export const adminRemove=(key,_id)=>{const n=adminList(key).filter(x=>x._id!==_id);localStorage.setItem('admin_'+key,JSON.stringify(n));return n}
export const getStats=()=>ls('admin_stats',null)
export const setStats=(v)=>{localStorage.setItem('admin_stats',JSON.stringify(v));return v}
// Registrations: which logged-in member registered/joined which event, visit, or course.
export const getRegs=(memberId)=>ls('nova_regs_'+memberId,[])
export const addReg=(memberId,item)=>{const l=getRegs(memberId);if(l.some(x=>x.name===item.name&&x.kind===item.kind))return l;const n=[...l,{...item,at:Date.now()}];localStorage.setItem('nova_regs_'+memberId,JSON.stringify(n));return n}
export const LGBH=[['Learn','Free educational resources and study support.'],['Grow','Communication, personality development and practical skills.'],['Build','Entrepreneurship, business workshops and real-world exposure.'],['Help','Community initiatives that allow students to give back to society.']]
export const HUB=[['📚','Free Notes','Subject-wise notes and study materials.'],['🗣️','English Speaking','Free English communication courses.'],['🔬','Science Projects','Project ideas, explanations and guidance.'],['🧠','Personality Development','Confidence, communication and leadership.'],['💼','Business Basics','Introduction to entrepreneurship and business thinking.'],['🎯','Career Exploration','Explore career paths after 11th and 12th Science.']]
export const COURSES=[['Spoken English – Beginner','English',12,'4 weeks',60],['Confidence & Communication','Personality',10,'3 weeks',35],['Business Basics','Business',8,'2 weeks',15],['Public Speaking','English',9,'3 weeks',0]]
export const PROJECTS=[['Solar Water Heater','Physics','Easy','₹300'],['Natural pH Indicators','Chemistry','Easy','₹100'],['Soil Health Monitor','Environmental','Medium','₹600'],['Arduino Smart Dustbin','Electronics','Medium','₹900']]
export const BIZ=[['💡','Business Building Workshops','Offline workshops on problem solving, marketing, sales, finance basics and leadership.'],['🏭','Industrial Visits','Visit companies, factories, startups and businesses.'],['🚀','Startup Exposure','Understand how real businesses are created.'],['🤝','Community Business','Collaborate on small community-based business ideas.']]
export const VISITS=[{n:'Manufacturing Industry',type:'Industrial Visit',loc:'Pune',date:'Coming soon',seats:'Limited student seats',el:'11th–12th Science'},{n:'Food Processing Unit',type:'Industrial Visit',loc:'Satara',date:'Coming soon',seats:'40 seats',el:'11th–12th Science'},{n:'Local Startup Studio',type:'Startup Visit',loc:'Kolhapur',date:'Previous visit',seats:'Completed',el:'All members'}]
export const HELP=[['🍱','Food Drive','Organise food collection and distribution for people who need support.'],['🌱','Tree Plantation Drive','Plant trees and join environmental activities.'],['🎬','NOVA Movie Drive','Community movie experiences where members come together.'],['🤝','Community Support','Student-led initiatives to help people and communities.'],['❤️','Helping Hand Campaigns','Special campaigns and volunteering activities.']]
export const CATS=['All','Education','Business','Industrial Visit','Social Impact','Entertainment','Community','Workshops']
export const EVENTS=[['Business Building Workshop','Business','Date TBA','10:30 AM','Pune','Seats available'],['Spoken English Kickoff','Education','Date TBA','4:00 PM','Online','Open'],['Tree Plantation Drive','Social Impact','Date TBA','7:30 AM','Satara','60 seats'],['Industrial Visit – Manufacturing','Industrial Visit','Coming soon','9:00 AM','Pune','Limited'],['NOVA Movie Day','Entertainment','Date TBA','5:00 PM','Kolhapur','Open'],['Science Project Clinic','Workshops','Date TBA','11:00 AM','Sangli','30 seats']]
export const COMM=['Student community','Discussion groups','Events','Workshops','Team activities','Project collaboration','Volunteer opportunities','Networking','Community challenges']
export const WHY=['Free Notes','Free English Speaking Course','Free Personality Development Programs','Free Science Project Guidance','Free Business Workshops','Industrial Visit Opportunities','Community Activities','Food Drives','Tree Plantation Drives','Student Networking','Entrepreneurship Exposure','Events & Experiences','Opportunities to Volunteer']
export const STATS=[[100,'%','Free learning resources'],[10,'+','Learning & development programs'],[1000,'+','Students goal'],['∞','','Opportunities to learn & help']]
export const FAQ=[['Is Project NOVA really free?','Yes. Membership and all learning resources are completely free.'],['Who can join?','Mainly 11th Science students in Maharashtra. 12th and college students are welcome too.'],['Do I need to attend everything?','No. Join what interests you: learning, workshops, visits or drives.'],['How do I register for a visit?','Become a member, then register from the Events section.']]
export const POINTS=[['Complete course',10],['Attend workshop',20],['Join tree plantation',30],['Food drive',30],['Industrial visit',25],['Help organise an event',50]]
export const BADGES=['🌱 Environment Champion','🤝 Helping Hand','💡 Young Entrepreneur','📚 Learning Star','🎯 Active Member','🚀 NOVA Leader']
export const DISTRICTS=['Ahilyanagar','Akola','Amravati','Beed','Bhandara','Buldhana','Chandrapur','Chhatrapati Sambhajinagar','Dharashiv','Dhule','Gadchiroli','Gondia','Hingoli','Jalgaon','Jalna','Kolhapur','Latur','Mumbai City','Mumbai Suburban','Nagpur','Nanded','Nandurbar','Nashik','Palghar','Parbhani','Pune','Raigad','Ratnagiri','Sangli','Satara','Sindhudurg','Solapur','Thane','Wardha','Washim','Yavatmal']

export const SCI_CATS=['Physics','Chemistry','Biology','Environmental Science','Technology','Innovation','Electronics','Computer Science']
export const SCI=[
['Solar Water Heater','Physics','Easy','₹300',['Plastic bottle','Black paint','Foil'],'Dark surfaces absorb sunlight and warm the water inside.',['Paint the bottle black','Add a foil reflector','Place in sunlight','Note the temperature every 15 minutes'],'Hot water can burn. Use gloves and adult supervision.','Water warms several degrees in an hour of sun.'],
['Natural pH Indicator','Chemistry','Easy','₹100',['Red cabbage','Warm water','Lemon juice','Baking soda'],'Cabbage pigment changes colour with acidity.',['Soak chopped cabbage in warm water','Strain the liquid','Add drops of lemon juice and baking-soda water','Compare colours'],'Use only kitchen items. Do not taste test liquids.','Acids turn it pink-red, bases turn it green-blue.'],
['Seed Germination Study','Biology','Easy','₹50',['Beans','Cotton','Cups','Water'],'Seeds need water, air and warmth to sprout.',['Place beans on wet cotton in cups','Keep one in light and one in dark','Water daily','Record growth'],'Wash hands after handling soil.','Seeds in light and dark grow differently.'],
['Rainwater Harvesting Model','Environmental Science','Medium','₹200',['Cardboard','Plastic sheet','Bottles','Sand'],'Collected rain can recharge groundwater.',['Build a roof from plastic sheet','Direct water into a bottle','Filter with sand layers','Measure collected water'],'Use blunt tools and supervision for cutting.','Measurable volume of collected water.'],
['Paper Bridge Load Test','Technology','Easy','₹50',['Paper','Tape','Coins'],'Shape and folds change how much load a structure holds.',['Make flat, folded and tube bridges','Add coins one by one','Record the load at failure'],'Keep hands clear when a bridge collapses.','Folded or tube shapes hold more.'],
['Foot-Pedal Hand-Wash Station','Innovation','Medium','₹400',['Bucket','Tap','Pedal lever','Rope'],'Hands-free design reduces touching shared surfaces.',['Fix tap to bucket','Connect pedal with rope','Test water flow','Improve the design'],'Secure the bucket so it cannot tip.','Water flows only while the pedal is pressed.'],
['Water-Level Alarm','Electronics','Medium','₹250',['9V battery','Buzzer','Wires','Container'],'Water completes a low-voltage circuit and sounds a buzzer.',['Connect buzzer and battery with two open wire ends','Place ends at the desired level','Fill with water slowly'],'Low-voltage only. Never use mains electricity.','Buzzer sounds when water touches both wires.'],
['Python Quiz Game','Computer Science','Easy','₹0',['Computer','Python'],'Loops and conditions turn questions into a game.',['Write 5 questions in a list','Loop through and check answers','Show the score'],'Take screen breaks.','A working quiz with a final score.']]
export const LIB={English:[['Spoken English – Beginner','NOVA Mentors','4 weeks',12],['Conversation Practice','NOVA Mentors','3 weeks',10],['Vocabulary Builder','NOVA Mentors','3 weeks',9],['Public Speaking','Guest Mentor','3 weeks',8]],'Personality Development':[['Confidence','NOVA Mentors','2 weeks',6],['Communication','NOVA Mentors','3 weeks',8],['Leadership','Guest Mentor','3 weeks',8],['Time Management','NOVA Mentors','2 weeks',6],['Presentation Skills','NOVA Mentors','2 weeks',7],['Teamwork','NOVA Mentors','2 weeks',6]],Business:[['Business Basics','Guest Mentor','2 weeks',8],['Marketing','Guest Mentor','3 weeks',9],['Sales','Guest Mentor','2 weeks',7],['Finance Basics','Guest Mentor','3 weeks',8],['Entrepreneurship','Guest Mentor','4 weeks',12]]}
export const JR=[['Courses completed',10],['Workshops attended',20],['Tree plantation drives',30],['Food drives',30],['Industrial visits',25],['Events organised',50]]